
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Thu Jan 08 23:27:35 PST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_WHILE = 55;
  public static final int T_INT_LITERAL = 65;
  public static final int T_FLOAT = 20;
  public static final int T_ELSE = 14;
  public static final int T_LTE = 31;
  public static final int T_STATIC = 48;
  public static final int T_RPAREN = 43;
  public static final int T_DELETE = 63;
  public static final int T_CONTINUE = 11;
  public static final int T_COUT = 12;
  public static final int T_SIZEOF = 45;
  public static final int T_NULLPTR = 36;
  public static final int T_FALSE = 19;
  public static final int T_INT = 25;
  public static final int T_MINUSMINUS = 33;
  public static final int T_EXTERN = 18;
  public static final int T_ASSIGN = 3;
  public static final int T_BAR = 58;
  public static final int T_RETURN = 42;
  public static final int T_NOT = 60;
  public static final int T_AND = 56;
  public static final int T_CONST = 10;
  public static final int T_SLASH = 46;
  public static final int T_COLONCOLON = 8;
  public static final int T_GT = 23;
  public static final int T_STRUCTDEF = 49;
  public static final int T_RBRACKET = 41;
  public static final int T_DOT = 13;
  public static final int EOF = 0;
  public static final int T_MINUS = 32;
  public static final int T_TILDE = 51;
  public static final int T_LBRACE = 27;
  public static final int error = 1;
  public static final int T_NEW = 62;
  public static final int T_SEMI = 44;
  public static final int T_ID_U = 67;
  public static final int T_FLOAT_LITERAL = 64;
  public static final int T_MOD = 34;
  public static final int T_RBRACE = 40;
  public static final int T_NEQ = 35;
  public static final int T_CIN = 6;
  public static final int T_COMMA = 9;
  public static final int T_STAR = 47;
  public static final int T_GTE = 24;
  public static final int T_ENDL = 15;
  public static final int T_EQU = 16;
  public static final int T_CARET = 59;
  public static final int T_BOOL = 4;
  public static final int T_PLUS = 38;
  public static final int T_EXIT = 17;
  public static final int T_LT = 30;
  public static final int T_STR_LITERAL = 66;
  public static final int T_THIS = 50;
  public static final int T_OR = 61;
  public static final int T_AMPERSAND = 57;
  public static final int T_BREAK = 5;
  public static final int T_TRUE = 52;
  public static final int T_ISTREAM = 26;
  public static final int T_FOREACH = 21;
  public static final int T_IF = 54;
  public static final int T_OSTREAM = 37;
  public static final int T_PLUSPLUS = 39;
  public static final int T_ARROW = 2;
  public static final int T_ID = 68;
  public static final int T_COLON = 7;
  public static final int T_FUNCTION = 22;
  public static final int T_VOID = 53;
  public static final int T_LBRACKET = 28;
  public static final int T_LPAREN = 29;
}

